"""
The docker-compose.yml file describes the services that make your app.
In this example those services are a web server and database.
The compose file also describes which Docker images these services use,
how they link together, any volumes they might need to be mounted inside the containers.
Finally, the docker-compose.yml file describes which ports these services expose.

This uses the build in development server to run your application on port 8000.
Do not use this in a production environment. For more information
"""
version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev